version: '3.8'

services:
  react-app:
    build:
      context: ./react-soft-dashboard
    environment:
      - HTTPS=true
      - GENERATE_SOURCEMAP=false
      - REACT_APP_BACKEND_SERVER=http://django-app:5005/api/
      - REACT_APP_GITHUB_OAUTH_CLIENT_ID=your-client-id
      - REACT_APP_GITHUB_OAUTH_CLIENT_SECRET=your-client-secret
      - REACT_APP_GITHUB_OAUTH_REDIRECT_URL=http://localhost:8080/authentication/sign-in
    networks:
      - web_network
    depends_on:
      - django-app

  django-app:
    container_name: appseed_app
    build:
      context: ./api-server-django
    ports:
      - "5005:5005"
    #expose:
    #  - "5005"  # Changed from 5005 to match your backend server URL
    networks:
      - db_network
      - web_network

  nginx:
    image: "nginx:latest"
    ports:
      - "8085:8085"  # Changed to standard 80 inside container
    volumes:
      - ./react-soft-dashboard/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react-app
      - django-app
    networks:
      - web_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge